name: Create Infra DB

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:

  create_infra:
    name: terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra
    steps:
      - name: Checkout
        uses: actions/checkout@v4
     
      - name: "Configure AWS Credentials" 
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.5

      - name: Inicializar Terraform
        run: |
          cd infra
          terraform init -reconfigure

      - name: Aplicar Terraform (Deploy)
        id: apply
        run: |
          cd infra
          terraform apply -auto-approve
