name: Terraform Pipeline - Destroy RDS

on:
  workflow_dispatch:  # Permite execução manual

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  terraform:
    name: Terraform RDS Destruction
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./env/homolog
    env:
      MONGODB_ATLAS_PUBLIC_KEY: ${{ secrets.MONGODB_ATLAS_PUBLIC_KEY }}
      MONGODB_ATLAS_PRIVATE_KEY: ${{ secrets.MONGODB_ATLAS_PRIVATE_KEY }}
      TF_VAR_projectName: ${{ secrets.DB_NAME }}
      TF_VAR_rdsUser: ${{ secrets.USERNAME }}
      TF_VAR_rdsPass: ${{ secrets.PASSWORD }}
      TF_VAR_dynamoName: ${{ secrets.DB_NAME_DY }}
    environment:
      name: production   # Proteção de ambiente configurada aqui!

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.7.0

    - name: Terraform Init
      run: terraform -chdir=terraform init

    # A pipeline vai pausar até você aprovar manualmente a destruição
    - name: Terraform Destroy
      run: terraform -chdir=terraform destroy -auto-approve