name: Terraform Pipeline - Create RDS

on:
  pull_request:
    branches:
      - main
  #workflow_dispatch: # Permite execução manual

jobs:
  terraform:
    name: Terraform RDS Deployment
    runs-on: ubuntu-latest

    environment:
      name: production   # Proteção de ambiente configurada aqui!

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.7.0

    - name: Set environment variables
      run: |
        echo "TF_VAR_projectName=${{ secrets.DB_NAME }}" >> $GITHUB_ENV  
        echo "TF_VAR_rdsUser=${{ secrets.USERNAME }}" >> $GITHUB_ENV
        echo "TF_VAR_rdsPass=${{ secrets.PASSWORD }}" >> $GITHUB_ENV
        echo "TF_VAR_dynamoName=${{ secrets.DB_NAME_DY }}" >> $GITHUB_ENV
        echo "TF_VAR_awsRegion=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV

    - name: Terraform Init
      run: terraform -chdir=terraform init

    - name: Terraform Plan
      run: terraform -chdir=terraform plan -out=tfplan

    # Aqui ele para e só continua se alguém aprovar no ambiente 'production'
    - name: Terraform Apply
      run: terraform -chdir=terraform apply -auto-approve tfplan
