name: Terraform Pipeline - Create RDS

on:
  pull_request:
    branches:
      - main
  #workflow_dispatch: # Permite execução manual

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  terraform:
    name: Terraform RDS Deployment
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./env/homolog
    env:
      MONGODB_ATLAS_PUBLIC_KEY: ${{ secrets.MONGODB_ATLAS_PUBLIC_KEY }}
      MONGODB_ATLAS_PRIVATE_KEY: ${{ secrets.MONGODB_ATLAS_PRIVATE_KEY }}

    environment:
      name: production   # Proteção de ambiente configurada aqui!

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.7

    - name: Set environment variables
      run: |
        echo "TF_VAR_projectName=${{ secrets.DB_NAME }}" >> $GITHUB_ENV  
        echo "TF_VAR_rdsUser=${{ secrets.USERNAME }}" >> $GITHUB_ENV
        echo "TF_VAR_rdsPass=${{ secrets.PASSWORD }}" >> $GITHUB_ENV
        echo "TF_VAR_dynamoName=${{ secrets.DB_NAME_DY }}" >> $GITHUB_ENV

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -out=tfplan

    # Aqui ele para e só continua se alguém aprovar no ambiente 'production'
    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
